# Generated by Django 5.0.9 on 2024-11-07 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0002_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('workload', models.FloatField()),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
