# Generated by Django 5.0.9 on 2024-11-07 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0004_rename_class_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='teacher_id',
            new_name='teacher',
        ),
    ]
