# Generated by Django 5.0.9 on 2024-11-07 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0005_rename_teacher_id_courses_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('topic', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.courses')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
