# Generated by Django 5.0.9 on 2024-11-07 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0006_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateTimeField()),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.courses')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursemanagement.student')),
            ],
        ),
    ]
