# Generated by Django 5.0.9 on 2024-11-08 21:39

from datetime import timedelta
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursemanagement', '0007_studentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='duration',
            field=models.DurationField(default=timedelta(hours=1)),
            preserve_default=False,
        ),
    ]
